/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "SCL_1_aliases.h"
#include "SCL_1.h"
#include "I2C_1.h"
#include "I2C_1_PVT.h"
#include "Encoder_1.h"
#include "Encoder_2.h"
#include "Encoder_3.h"
#include "Encoder_4.h"
#include "Encoder_5.h"
#include "Encoder_6.h"
#include "Encoder_7.h"
#include "Clock_1.h"
#include "Enc_1_aliases.h"
#include "Enc_1.h"
#include "Enc_2_aliases.h"
#include "Enc_2.h"
#include "Enc_3_aliases.h"
#include "Enc_3.h"
#include "Enc_4_aliases.h"
#include "Enc_4.h"
#include "Enc_5_aliases.h"
#include "Enc_5.h"
#include "Enc_6_aliases.h"
#include "Enc_6.h"
#include "Enc_7_aliases.h"
#include "Enc_7.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

